######################################################################
# Automatically generated by qmake (3.0) mer ott 1 00:07:52 2014
######################################################################

QT += quick
TEMPLATE = app
TARGET = cpp-exported-object-logger
INCLUDEPATH += .

# Input
SOURCES += main.cpp
