######################################################################
# Automatically generated by qmake (3.0) mer ott 1 15:45:41 2014
######################################################################

QT += core-private qml-private quick
TEMPLATE = app
TARGET = v4-injection-2
INCLUDEPATH += .

# Input
SOURCES += main.cpp
