######################################################################
# Automatically generated by qmake (3.0) mer ott 1 15:42:19 2014
######################################################################

QT += quick
TEMPLATE = app
TARGET = defaultlogging
INCLUDEPATH += .

# Input
SOURCES += main.cpp
