######################################################################
# Automatically generated by qmake (3.0) mer ott 1 11:55:44 2014
######################################################################
QT += core-private gui-private qml-private qml quick
TEMPLATE = app
TARGET = v4-injection
INCLUDEPATH += .

# Input
SOURCES += main.cpp
